INSERT INTO `salle` (`id_salle`, `titre`, `description`, `photo`, `pays`, `ville`, `adresse`, `cp`, `capacite`, `categorie`) VALUES
(1, 'l\'atrium ', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/007.jpg', 'france', 'paris', '20 RUE DE L\'EST ', 75020, 30, 'reunion'),
(2, 'le leader', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/008.jpg', 'france', 'paris', '11 Rue Laugier', 75017, 23, 'reunion'),
(3, 'l\'auditrium', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/005.jpg', 'france', 'paris', '85 RUE DE LA FONTAINE AU ROI ', 75011, 45, 'reunion'),
(4, 'panorama', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition ', 'photos/006.jpg', 'france', 'Paris', '84 Avenue de Wagram', 75017, 56, 'reunion'),
(5, 'la vedette', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/001.jpg', 'france', 'paris', '49 BOULEVARD VOLTAIRE ', 75011, 76, 'formation'),
(6, 'prestige', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/002.jpg', 'france', 'paris', '47 Rue Censier', 75005, 66, 'reunion'),
(7, 'ma sale', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/003.jpg', 'france', 'paris', 'MSP JEAN JAURÈS 9 SENTE DES DORÉES', 75019, 9, 'bureau'),
(8, 'cezanne', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/004.jpg', 'france', 'paris', '34 Boulevard du Temple', 75011, 21, 'formation'),
(9, 'sequoia', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/009.jpg', 'france', 'paris', '59 Rue Boissiere', 75116, 22, 'bureau'),
(10, 'cassel', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/010.jpg', 'france', 'paris', '10 Rue de la Paix', 75002, 16, 'reunion'),
(11, 'taillanda', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/021.jpg', 'france', 'marseille', '4 RUE CAPITAINE JEAN CROISA', 13009, 65, 'reunion'),
(12, 'Suanluang', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'phots/022.jpg', 'france', 'marseille', '48 AVENUE DE LA CORSE', 13007, 12, 'formation'),
(13, 'Sukhumvit', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/023.jpg', 'france', 'marseille', '109 AVENUE DE LA ROSE', 13013, 75, 'reunion'),
(14, 'CHIANGMAI', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/024.jpg', 'france', 'marseille', '20 RUE COLBERT', 13001, 57, 'formation'),
(15, 'PHUKET', ' Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/025.jpg', 'france', 'marseille', '10 BOULEVARD D ARRAS', 13004, 12, 'bureau'),
(16, 'Muang', ' Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/026.jpg', 'france', 'marseille', '125 BOULEVARD VALETTE', 13013, 87, 'reunion'),
(17, 'Talad-Nua', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/027.jpg', 'france', 'marseille', '1 RUE AUGUSTIN FRESNEL', 13013, 12, 'bureau'),
(18, 'Wattana', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/028.jpg', 'france', 'marseille', '1 RUE AUGUSTIN FRESNEL', 13013, 12, 'reunion'),
(19, 'Road', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/029.jpg', 'france', 'marseille', '196 CHEMIN DE GIBBES', 13014, 23, 'bureau'),
(20, 'Sukhumvi', ' Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/030.jpg', 'france', 'marseille', ' 173 CHEMIN DE SAINTE MARTHE', 13014, 8, 'bureau'),
(21, ' lela baya', ' Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/031', 'france', 'lyon', 'COURS GAMBETTA', 69003, 23, 'bureau'),
(22, 'le premier', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/032.jpg', 'france', 'lyon', '2 RUE MASARYK', 69009, 67, 'reunion'),
(23, 'ma zouhour', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/033.jpg', 'france', 'lyon', '51 BIS RUE SERGENT MICHEL BERTHET', 69009, 45, 'reunion'),
(24, 'my way', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/034.jpg', 'france', 'lyon', '330 RUE DU DOYEN GEORGES CHAPAS', 69009, 12, 'formation'),
(25, 'galaxy', ' Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/035.jpg', 'france', 'lyon', '153 BIS RUE JOLIOT CURIE', 69005, 23, 'formation'),
(26, 'novotel', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/036.jpg', 'france', 'lyon', '31 RUE BELLECOMBE', 69006, 98, 'reunion'),
(27, 'regency', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition .', 'photos/037.jpg', 'france', 'lyon', '11 RUE ANTOINE LUMIÈRE', 69008, 87, 'formation'),
(28, 'la marquise', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition', 'photos/038.jpg', 'france', 'lyon', '26 RUE DUQUESNE', 69006, 87, 'reunion'),
(29, 'opera', 'Le Lorem Ipsum est simplement du faux texte employé dans la composition ', 'photos/039.jpg', 'france', 'lyon', '31 RUE BELLECOMBE', 69006, 23, 'bureau');